const  ActionTypes = {
    GET_IMDB_DATA : 'GET_IMDB_DATA',
    GET_SHOW_LIST: 'GET_SHOW_LIST',
    SET_SEARCH_RESULT: 'SET_SEARCH_RESULT',
    CLEAR_DETAILS_DATA: 'CLEAR_DETAILS_DATA'
};

export default ActionTypes;
